
log_format altmain '$remote_addr/$http_x_real_ip - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent"';

access_log /var/log/nginx/alt_access.log altmain;

server {
    root /usr/share/nginx/html;
    listen 0.0.0.0:80;
    location / {}
}
