# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Unittests

on: [push]

jobs:
  runtests:

    # Machine environment:
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Use Node.js 20
      uses: actions/setup-node@v4.0.2
      with:
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
        node-version: 20.11.0
    - name: Update Angular CLI
      run: npm install -g @angular/cli@latest
    - name: Install dependencies
      run: yarn install
  # The linter got lost in the upgrade to ng14.
  #  hoepfully we can find it againg
  #  - name: Lint
  #    run: npm run lint
    - name: Test
      run: yarn test -- --configuration=ci
